title: Valentin Zambelli
description: > # this means to ignore newlines until "baseurl:"
  I am a freelance developer in Berlin working on Machine Learning, Data Engineering and Blockchain projects. 
  
permalink: ':title/'
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
site-twitter:  #if your site has a twitter account, enter it here

# Author Settings
author: Valentin Zambelli # add your name
author-img: valentin.png # add your photo
about-author: I am a freelance developer in Berlin working on Machine Learning, Data Engineering and Blockchain projects.  # add description
social-twitter: vazamb # add your Twitter handle
social-facebook: # add your Facebook handle
social-github: vazamb # add your Github handle
social-linkedin: valentin-zambelli # add your Linkedin handle
social-email: valentin.zambelli[at]gmail.com # add your Email address

# Disqus
discus-identifier: mr-brown # add your discus identifier

# Tracker
analytics: # Google Analytics

# Build Settings
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji

paginate: 8
paginate_path: "/page/:num"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
